name: bimarestan
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  another_flushbar: ^1.10.29
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: 5.1.0
  flutter_svg: ^1.1.6
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_sign_in: ^5.4.2
  image_picker: ^0.8.6
  injectable: ^2.0.1
  internet_connection_checker: ^1.0.0+1
  intl: 0.17.0
  json_annotation: ^4.7.0
  modal_progress_hud_nsn: ^0.2.1
  path: 1.8.2
  path_provider: ^2.0.11
  pinput: ^2.2.16
  pretty_dio_logger: ^1.1.1
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  stacked_services: ^0.9.8
  tuple: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  injectable_generator: ^2.0.1
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_intl:
  enabled: true
  use_deferred_loading: true
  class_name: AppLocalizations
  output_dir: lib/localizations
  arb_dir: lib/localizations/l10n
